### ISSUE TITLE
Save results 

### ISSUE THREAD

**Issue by josesovaz** [marcjwilliams1/SubClonalSelection.jl#16]
Hello again Marc,

I am trying to perform SubClonalSelection analyses with a high number of iterations and lower convergence values. I was wondering if it is possible to save the results (csv files and plots) not only at the end of the analysis, but also while it is still in progress (for example, saving results between population number 1 and population number 2 and so on). It could be useful (at least for me), for example, if I set a number of iterations and I want to check the last results (of the previous population number) and decide to stop or not the analysis.

Thank you,

Jose Luis

**Comment by marcjwilliams1** [comment]
I've just updated everything to v1.0, and included a fix for this. Everything works for me, but haven't got the CI up and running yet so let me know if there are any issues

**Comment by josesovaz** [comment]
Thank you Marc, I am going to use this new version during this week
