### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by sbamin** [marcjwilliams1/SubClonalSelection.jl#23]
Hi Marc,

I get an error of missing project file while installing package in REPL mode. Looks like Pkg.clone has been deprecated. I am using julia v1.4.0.

```julia
(@v1.4) pkg> add https://github.com/marcjwilliams1/SubClonalSelection.jl
    Cloning git-repo `https://github.com/marcjwilliams1/SubClonalSelection.jl`
   Updating git-repo `https://github.com/marcjwilliams1/SubClonalSelection.jl`
ERROR: could not find project file in package at https://github.com/marcjwilliams1/SubClonalSelection.jl
```

I was able to install GpABC using `add https://github.com/tanhevg/GpABC.jl`. I am new to julia and  perhaps adding [Project.toml](https://github.com/tanhevg/GpABC.jl/blob/master/Project.toml) should fix an issue.

take care and hope things are ok on your end.

**Comment by marcjwilliams1** [comment]
Hi @sbamin It should be fixed now. Thanks for flagging.

You might be interested in trying this package out btw which we have just released (it's still going through some minor changes): https://github.com/caravagn/mobster

It's much faster and has many more capabilities than this package. Also lots more docs, should hopefully be much easier to use.

Any further issues or questions re this or MOBSTER do reach out.

Cheers
Marc

**Comment by sbamin** [comment]
Great and it worked!

Thanks for forwarding mobster pkg. I will take a look and preprint. Like the idea of developing evoverse ecosystem 👍 https://github.com/caravagn/evoverse.datasets
